//schemas

const  mongoose = require('mongoose');

const studentshema = mongoose.Schema({
    first_name:{
        type:String,
        required : true
    },
    last_name:{
        type:String,
        required:true
    },
    middle_name:{
        type:String,
        required:true
    },
    parents_name:{
        type:String,
        required:true
    },
    phone_no:{
        type:Number,
        required:true
    },
    email_id:{
        type:String,
        required:true
    },
    date_of_birth:{
        type:Date,
        required:true
    },
    caste:{
        type:String,
        required:true
    },
    parents_contact_no:{
        type:Number,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    gender:{
        type:String,
        required:true,
        enum:['M','F']
    },
    school_name:{
        type:String,
        required:true
    },
    tenth_percentage:{
        type:Number,
        required:true
    },
    jr_college_name:{
        type:String,
        required:true
    },
    hsc_percentage:{
        type:Number
    },
    diploma_percentage:{
        type:Number
    },
    college_name:{
        type:String,
        required:true
    },
    current_field:{
        type:String,
        required:true
    },
    first_year_firstsem:{
        type:Number
    },
    first_year_secondsem:{
        type:Number
    },
    second_year_firstsem:{
        type:Number,
        required:true
    },
    second_year_secondsem:{
        type:Number,
        required:true
    },
    third_year_firstsem:{
        type:Number,
        required:true
    },
    third_year_secondsem:{
        type:Number,
        required:true
    },
    previous_backlog:{
        type:Number,
        required:true
    },
    current_backlog:{
        type:Number,
        required:true
    },
    year_of_admission:{
        type:Number,
        required:true
    },
    passing_year:{
        type:Number,
        required:true
    },
    spoken_languages:{
        type:[String]
    },
    software_known:{
        type:[String]
    },
    achivements:{
        type:[String]
    },
    urls:{
        type:[String]
    },
    projects:{
        type:[String]
    },
    certification:{
        type:[String]
    },    
    career_obj:{
        type:String
    },
    strength:{
        type:[String]
    },
    placed_status:{
        type:String,
        enum:['Yes','No'],
        required:true
    },
    packagee:{
        type:Number
    },
    user_name:{
        type:String,
        required:true
    },
    pass_word:{
        type:String,
        required:true
    },
    verify:{
        type:String,
        enum:['Yes','No'],
        default:'No'
    }
});

const c = module.exports = mongoose.model('students', studentshema);
